a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('Só tem espaços: ', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumerico?', a.isalnum())
print('Está em maiusculas? ', a.isupper())
print('Esta em minusculas? ', a.islower())
print('esta captalizado? ', a.istitle())